version: "3"
services:
  # Définition du conteneur servant le front (application Vue.js)
  front:
    build:
      context: ./Client/app
      dockerfile: Dockerfile
    image: appli/vue
    container_name: front
    ports:
      - "8080:8080"
    # On attend que le conteneur back soit prêt avant de démarrer le front
    depends_on:
      - back
  # Définition du conteneur servant le back (application Node.js pour l'API REST et le serveur WebSocket)
  back:
    build:
      context: ./Server
      dockerfile: Dockerfile
    image: appli/back
    container_name: back
    ports:
      - "3000:3000"
      - "9000:9000"
    # On attend que le conteneur MongoDB soit prêt avant de démarrer le back
    depends_on:
      - mongo
    # Permet l'accès à la bdd depuis le code sans avoir à spécifier l'adresse de la bdd
    external_links:
      - mongo

  # Définition du conteneur MongoDB, utilisant une image déjà prête de monogdb
  mongo:
    image: mongo
    container_name: mongo
    # La base de données se relancera en cas de crash
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db